### ISSUE TITLE
'--ignore-watch' option not supported

### ISSUE THREAD

**Issue by eightyfive** [Unitech/pm2-dev#1]
I maybe confused but it seems that the `--ignore-watch` option is not supported by `pm2-dev`.

Tried to run:

```
$ pm2-dev run server.js --ignore-watch='^.*\.log$ es6 client public \.git'
```

Got:

```
error: unknown option `--ignore-watch'
```

Is there a way to ignore a set of files in development mode?

Thanks

**Comment by afbayonac** [comment]
the best is have the package.json configured 
http://pm2.keymetrics.io/docs/usage/application-declaration/

**Comment by eightyfive** [comment]
Looking for a solution for `pm2-**dev**`, which is not mentioned in above documentation. Have you tried your `ecosystem.json` (not package.json...) solution with `pm2-dev`? Thx.

**Comment by umaxfun** [comment]
Both approaches do not work for me :(

**Comment by Robert-Ernst** [comment]
pm2-dev documentation is horrible

Rather read the source:
https://github.com/Unitech/pm2/blob/master/lib/DevCli.js
